In [1]:
#Importing Libraries
import pandas as pd
import numpy as np
import cv2
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.multiclass import OneVsRestClassifier

In [2]:
#Importing and Loading Datasets
from keras.datasets import mnist
(X_train,y_train), (X_test,y_test) = mnist.load_data()

In [3]:
#Splitting Data based on N Value
X_train=X_train[:6800]
y_train=y_train[:6800]
from sklearn.model_selection import train_test_split

In [4]:
X_train.shape

(6800, 28, 28)

In [5]:
#Reshaping the data
#Source :  https://stackoverflow.com/questions/34972142/sklearn-logistic-regression-valueerror-found-array-with-dim-3-estimator-expec
nsamples, nx, ny =X_train.shape
X_train = X_train.reshape((nsamples,nx*ny))
nsamples2, nx2, ny2 =X_test.shape
X_test = X_test.reshape((nsamples2,nx2*ny2))

In [6]:
#Defining X and y
X=X_train
y=y_train

In [7]:
X.shape

(6800, 784)

In [8]:
#Initializing 10*10 base confusion matrix
cm_prev = np.zeros((10,10))
for i in range(32):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=None,shuffle=True)
    
    #Fitting and Training the Model
    #Source : https://scikit-learn.org/stable/auto_examples/neighbors/plot_classification.html#sphx-glr-auto-examples-neighbors-plot-classification-py
    #Source : https://scikit-learn.org/stable/modules/generated/sklearn.multiclass.OneVsRestClassifier.html
    knn=OneVsRestClassifier( KNeighborsClassifier(n_neighbors=31))
    knn.fit(X_train, y_train)
    y_pred = knn.predict(X_test)
    
    
    #Calculating Confusion matrix and accuracy for each value of K
    acc=accuracy_score(y_test,y_pred)
    print("Accuracy when k=",i," is",acc)
    print("\n")
    print("confusion matrix when k=",i)
    print("\n")
    print(confusion_matrix(y_test, y_pred))
    acc=accuracy_score(y_test,y_pred)
    print("\n")
    cm_now = cm_prev + confusion_matrix(y_test, y_pred)
    cm_prev = cm_now
   


    
#Formatting the elements in the matrix
#Source:https://stackoverflow.com/questions/63675559/how-can-i-adjust-space-between-elements-of-numpy-array
#Calculating and printing Average Confusion Matrix
np.set_printoptions(formatter={'all': lambda x: " {:.2f} ".format(x)})
print("\n Average Confusion Matrix with using libraries \n")
print(cm_now/31)

Accuracy when k= 0  is 0.9220588235294118


confusion matrix when k= 0


[[132   0   0   0   1   0   0   0   0   0]
 [  0 158   0   0   0   0   0   0   0   0]
 [  0  11 109   4   1   0   0   4   2   1]
 [  1   2   0 121   0   3   0   4   1   4]
 [  0   2   0   0 113   2   0   0   0   6]
 [  1   0   0   5   0 107   2   0   0   3]
 [  1   0   0   1   0   0 139   0   0   0]
 [  0   3   0   0   0   1   0 123   0   5]
 [  2   6   0   6   0   7   2   0 116   6]
 [  1   0   0   0   2   0   0   3   0 136]]


Accuracy when k= 1  is 0.913235294117647


confusion matrix when k= 1


[[124   0   0   1   1   1   1   0   1   0]
 [  0 140   0   1   1   0   0   1   0   0]
 [  1   7 134   0   1   1   1   4   1   2]
 [  0   3   0 119   0   2   0   2   0   3]
 [  0   5   0   0 126   0   1   0   0  11]
 [  1   2   0   5   0 103   2   0   0   3]
 [  0   1   0   0   0   1 129   0   0   0]
 [  0   6   0   0   2   0   0 129   0   6]
 [  1   8   0   9   0   3   0   0 108   1]
 [  2   1   0   3   2   0   1   4  